language: ruby
cache: bundler
sudo: false

before_install:
  - gem install --system
  - gem install bundler

rvm:
  - &ruby2.5 2.5.3
  - &ruby2.3 2.3.8

matrix:
  include:
    - rvm: *ruby2.5
      name: "Ruby 2.5.3"
    - rvm: *ruby2.3
      name: "Ruby 2.3.8"

branches:
  only:
    - master

script:
  - echo "Hello Travis"