language: ruby

sudo: false

rvm:
 - 2.6
 - 2.5
 - 2.4
 - jruby

before_install:
  - gem install bundler
  - bundler --version

install:
  - bundler install --jobs=4 --retry=3 --path vendor/bundle

cache: bundler

branches:
  only:
    - master