---

version: "{build}"

install:
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem update --system 2.6.14 --no-document
  - gem install bundler --no-document
  - bundle install --jobs 4 --retry 3

build: off

test_script:
  - bundle exec rake spec

environment:
  matrix:
    - ruby_version: '23'
    - ruby_version: 23-x64
    - ruby_version: '25'
    - ruby_version: 25-x64