
version: 2.1
aliases:
  - &defaults
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/grease

  - &restore_cache
    restore_cache: 
    keys:
      - v1-bundle-{{ .Branch }}-{{ .Revision }}-{{ checksum "Gemfile.lock" }}
      - v1-bundle-{{ .Branch }}-{{ .Revision }}-
  - &save_cache
    save_cache: 
    paths:
      - ./vendor/bundle
    key: v1-dependencies-{{ checksum "Gemfile.lock" }}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Installing Dependencies...
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - *save_cache
      - run:
          name: Let's Say Hello
          command: |
            echo "Hello CircleCI"

workflows:
  version: 2.1
  build_test:
    jobs:
      - build